name: Documentation
description: "Deploys the documentation."

runs:
  using: composite

  steps:
    - name: Setup Pages
      uses: actions/configure-pages@v3
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: './doc/_site'
        
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2