name: Build Documentation
description: "Build the documentation."

runs:
  using: composite

  steps:
    - name: Build Documentation
      uses: JetBrains/writerside-github-action@v4
      with:
        instance: doc/MrKWatkins.Ast
        artifact: webHelpMRKWATKINS.AST2-all.zip
        docker-version: 232.10275

    - name: Upload documentation
      uses: actions/upload-artifact@v4
      with:
        name: docs
        path: |
          artifacts/webHelpMRKWATKINS.AST2-all.zip
          artifacts/report.json
        retention-days: 7