name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version Number'
        required: true
        type: string

permissions:
  checks: write
  contents: write
  id-token: write
  pages: write

jobs:
  Release:
    name: Release ${{ inputs.version }}
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Publish to NuGet
        uses: MrKWatkins/nuget-publish@main
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
          version: ${{ inputs.version }}
          directory: src

      - name: Build
        uses: MrKWatkins/dotnet-build@main
        with:
          name: MrKWatkins.Ast
          directory: src

      - name: Install Sesharp
        run: dotnet tool install --tool-path ./.tools MrKWatkins.Sesharp.Tool

      - name: Make API Docs Directory
        run: mkdir -p doc/docs/API

      - name: Generate API Docs
        run: ./.tools/sesharp src/MrKWatkins.Ast/bin/Release/net10.0/MrKWatkins.Ast.dll --output doc/docs/API --repository https://github.com/MrKWatkins/Ast

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: doc/mkdocs.yml
          REQUIREMENTS: doc/requirements.txt